FROM ubuntu:16.04

RUN apt-get update \
 && apt-get install -y \
    git build-essential software-properties-common sudo \
 && add-apt-repository -y ppa:ubuntu-toolchain-r/test \
 && apt-get update \
 && apt-get install -y gcc-7 \
 && cd /usr/bin/ \
 && rm gcc \
 && ln -s gcc-7 gcc \
 && git clone https://gerrit.fd.io/r/vpp /vpp

ADD build.env /

RUN . /build.env \
 && cd /vpp \
 && git pull \
 && git checkout ${VPP_COMMIT} \
 && UNATTENDED=y make vpp_configure_args_vpp='--disable-japi --disable-vom' install-dep bootstrap pkg-deb \
 && cd build-root \
 && bash -c "dpkg -i {vpp,vpp-plugins,vpp-lib,vpp-dev}_$(git describe --tags | sed -e s/-/~/2 -e s/^v//)_amd64.deb"
